### ISSUE TITLE
conf error

### ISSUE THREAD

**Issue by yangsishu** [logstash-plugins/logstash-output-webhdfs#22] opened 2016-07-29 06:59 UTC
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:
- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
  input {
  ...
  }
  filter {
  ...
  }
  output {
  webhdfs {
    server => "127.0.0.1:50070"         # (required)
    path => "/user/logstash/dt=%{+YYYY-MM-dd}/logstash-%{+HH}.log"  # (required)
    user => "hue"                       # (required)
  }
  }

this conf is error
- Sample Data:
- Steps to Reproduce:

**Comment by yangsishu** [comment] 2016-07-29 07:00
server => "127.0.0.1:50070"  is error

host = > "127.0.0.1"
port = > 57007

**Comment by dstore-dbap** [comment] 2016-08-01 10:57
@yangsishu Thanks for taking the time to open this issue. Still. I'm going to close this one since it is a duplicate of https://github.com/logstash-plugins/logstash-output-webhdfs/issues/9. Please follow this issue for updates concerning  this bug.

Thanks again and take care,
Björn

**Closed as completed by dstore-dbap** 2016-08-01 10:57 UTC
