### ISSUE TITLE
logstash-output-webhdfs不支持hdfs的ha模式

### ISSUE THREAD

**Issue by gabry-lab** [logstash-plugins/logstash-output-webhdfs#23] opened 2016-08-31 08:12 UTC
logstash-output-webhdfs的host参数只能设置一个ip地址，这在ha模式下非常不方便，也不合理。
如果hdfs是ha模式，当设置的namenode编程standby时，此次导入就失败了，希望host参数支持多个ip配置

**Comment by jordansissel** [comment] 2016-08-31 23:35
Google translate says: 

> host parameters logstash-output-webhdfs can only set a ip address, it is very inconvenient mode in ha, but also unreasonable. If hdfs is ha mode, when set namenode programming standby, the import fails, and hope to support multiple ip host configuration parameters

**Comment by dstore-dbap** [comment] 2016-09-08 11:05
Hi gabrywu ,

thanks for opening an issue here. Sadly I'm unable to reproduce your issue. Here is the respective  configuration for the webhdfs output:
`output {
    webhdfs {
        workers => 1
        host => "webhdfs-node1.dbap.de"
        standby_host => "webhdfs-node2.dbap.de"
    user => "test"
        path => "/user/test/test_%{[@metadata][thread_id]}.log"
    single_file_per_thread => true
    flush_size => 50
        idle_flush_time => 10
        retry_interval => 0.5
    retry_times => 5
    }
}`
Starting logstash with this configuration seems ok. Data ends up as expected in the configured file. Shutting down webhdfs service on webhdfs-node1.dbap.de triggers switch to webhdfs-node2.dbap.de.

Please note that both hostnames need to be resolvable on the host running logstash.

If you could provide more detail as to your logstash version, configuration and encountered error message I will have a closer look.

Thanks again and take care,
Björn

Translated with translate.google.de:
 嗨gabru，
感谢这里打开的问题。可悲的是，我无法重现您的问题。下面是respectivement webhdfs输出的配置：
`output {
    webhdfs {
        workers => 1
        host => "webhdfs-node1.dbap.de"
        standby_host => "webhdfs-node2.dbap.de"
    user => "test"
        path => "/user/test/test_%{[@metadata][thread_id]}.log"
    single_file_per_thread => true
    flush_size => 50
        idle_flush_time => 10
        retry_interval => 0.5
    retry_times => 5
    }
}`

这种配置启动logstash似乎确定。数据最终如预期中的配置文件。关闭webhdfs上webhdfs-node1.dbap.de服务触发楚webhdfs-node2.dbap.de。

请注意，主机名都必须在主机上运行logstash解析。

如果你能提供更多的细节，以你的logstash版本，配置和遇到的错误消息我想仔细看看。

再次感谢和照顾，
Björn

**Comment by dstore-dbap** [comment] 2016-11-10 13:05
As I did not hear anything from you since my last post, I will close this issue now. If the problem still persists, please open a new issue.

Thanks again and take care,
Björn

**Closed as completed by dstore-dbap** 2016-11-10 13:05 UTC
